Test stdout rerouting in docker

diff --git a/.github/workflows/master.yaml b/.github/workflows/master.yaml
--- a/.github/workflows/master.yaml
+++ b/.github/workflows/master.yaml
@@ -33,7 +33,18 @@ jobs:
 
       - name: Build and Push Docker image
         # run: docker buildx build . --push --progress=plain --build-arg GIT_COMMIT=${{ github.sha }} -t omnimodular.azurecr.io/omnicoder/document-matching:latest | { read CID; echo digest=$CID >> $GITHUB_OUTPUT; }
-        run: docker buildx build . --push --progress=plain --build-arg GIT_COMMIT=${{ github.sha }} -t omnimodular.azurecr.io/omnicoder/document-matching:latest
+        run: |
+          docker buildx build . --push --progress=plain --build-arg GIT_COMMIT=${{ github.sha }} -t omnimodular.azurecr.io/omnicoder/document-matching:latest > stdout.txt
+          echo "stdout BEGIN"
+          cat stdout.txt
+          echo "stdout END"
+          echo "$GITHUB_OUTPUT"
+          if grep -q "sha256:" buildx_stdout.txt; then
+            echo "Digest found in stdout."
+          else
+            echo "Digest NOT found in stdout. This is likely the problem."
+            exit 1
+          fi
         id: build
 
       - name: Dispatch repository event
